# Generated by Django 4.1.7 on 2023-03-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoTranspor_IVYt3', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='Destination',
            new_name='destination',
        ),
        migrations.AddField(
            model_name='customers',
            name='amount',
            field=models.CharField(default=1000, max_length=50),
        ),
    ]
